// <auto-generated />
using System;
using CsvProcessor.Models.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CsvProcessor.Migrations
{
    [DbContext(typeof(CsvContext))]
    [Migration("20260116095906_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "timescaledb");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);


            modelBuilder.Entity("CsvProcessor.Models.DbModels.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<bool?>("ProcessingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processing_status");

                    b.Property<DateTime?>("UploadTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("files_pkey");

                    b.HasIndex(new[] { "Filename" }, "files_filename_key")
                        .IsUnique();

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("CsvProcessor.Models.DbModels.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageExecutionTime")
                        .HasColumnType("numeric")
                        .HasColumnName("average_execution_time");

                    b.Property<decimal?>("AverageValue")
                        .HasColumnType("numeric")
                        .HasColumnName("average_value");

                    b.Property<TimeSpan?>("DeltaSeconds")
                        .HasColumnType("interval")
                        .HasColumnName("delta_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MedianValue")
                        .HasColumnType("numeric")
                        .HasColumnName("median_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric")
                        .HasColumnName("min_value");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("results_pkey");

                    b.HasIndex(new[] { "FileName" }, "idx_results_file_name");

                    b.HasIndex(new[] { "FileName" }, "results_file_name_key")
                        .IsUnique();

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("CsvProcessor.Models.DbModels.Value", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("ExecutionTime")
                        .HasColumnType("numeric")
                        .HasColumnName("execution_time");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer")
                        .HasColumnName("file_id");

                    b.Property<decimal>("Value1")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasIndex("FileId");

                    b.HasIndex(new[] { "Date" }, "idx_values_date");

                    b.HasIndex(new[] { "Date" }, "values_date_idx")
                        .IsDescending();

                    b.ToTable("values", (string)null);
                });

            modelBuilder.Entity("CsvProcessor.Models.DbModels.Value", b =>
                {
                    b.HasOne("CsvProcessor.Models.DbModels.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("values_file_id_fkey");

                    b.Navigation("File");
                });
#pragma warning restore 612, 618
        }
    }
}
